# Analisis de sentimientos Twitter

In [1]:
import numpy as np
import sklearn
import scipy

print("NumPy:", np.__version__)
print("scikit-learn:", sklearn.__version__)

NumPy: 1.26.4
scikit-learn: 1.7.0

In [2]:
!pip install spacy

Requirement already satisfied: spacy in c:\users\soportedrai\anaconda3\lib\site-packages (3.8.7)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (0.9.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (4.66.5)
Requirement already satisfied: numpy>=1.19.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (2.8.2)
Requirement already satisfied: jinja2 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (3.1.4)
Requirement already satisfied: setuptools in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (75.1.0)
Requirement already satisfied: packaging>=20.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (24.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy) (3.5.0)
Requirement already satisfied: language-data>=1.2 in c:\users\soportedrai\anaconda3\lib\site-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\soportedrai\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\soportedrai\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\soportedrai\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.4.26)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Collecting numpy>=1.19.0 (from spacy)
  Using cached numpy-2.3.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: colorama in c:\users\soportedrai\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.1.7)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.21.1)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (5.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from jinja2->spacy) (2.1.3)
Requirement already satisfied: marisa-trie>=1.1.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.2.1)
Using cached numpy-2.3.1-cp312-cp312-win_amd64.whl (12.7 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
Successfully installed numpy-2.3.1

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Soportedrai\anaconda3\Lib\site-packages\~-mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Soportedrai\anaconda3\Lib\site-packages\~-mpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.3.1 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.3.1 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.3.1 which is incompatible.
scipy 1.13.1 requires numpy<2.3,>=1.22.4, but you have numpy 2.3.1 which is incompatible.

In [3]:
# Librerias:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [4]:

!python -m spacy download es_core_news_md

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\spacy\__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\spacy\errors.py", line 3, in <module>
    from .compat import Literal
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\spacy\compat.py", line 4, in <module>
    from thinc.util import copy_array
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\thinc\__init__.py", line 5, in <module>
    from .config import registry
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\thinc\config.py", line 5, in <module>
    from .types import Decorator
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\thinc\types.py", line 27, in <module>
    from .compat import cupy, has_cupy
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\thinc\compat.py", line 99, in <module>
    import h5py
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\h5py\__init__.py", line 45, in <module>
    from ._conv import register_converters as _register_converters, \
  File "h5py\\_conv.pyx", line 1, in init h5py._conv
  File "h5py\\h5r.pyx", line 1, in init h5py.h5r
  File "h5py\\h5p.pyx", line 1, in init h5py.h5p
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [5]:
import spacy

In [6]:
pip install pandas

Requirement already satisfied: pandas in c:\users\soportedrai\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\soportedrai\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\soportedrai\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\soportedrai\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd

# EDA : Análisis exploratorio de lo que tenemos.

In [11]:
columns = ['id','brand','label','text']
# agregar las columnas al dataset

df = pd.read_csv('./datasets/twitter_validation.csv', names = columns)

print(df.info())
display(df.head())
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      1000 non-null   int64
 1   brand   1000 non-null   object
 2   label   1000 non-null   object
 3   text    1000 non-null   object
dtypes: int64(1), object(3)
memory usage: 31.4+ KB
None

,id,brand,label,text
0,3364,Facebook,Irrelevant,I mentioned on Facebook that I was struggling ...
1,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
2,8312,Microsoft,Negative,@Microsoft Why do I pay for WORD when it funct...
3,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
4,4433,Google,Neutral,Now the President is slapping Americans in the...

(1000, 4)

In [12]:
# VER LA DISTRIBUCIÓN DE SENTIMIENTOS: 
df['label'].value_counts()

label
Neutral       285
Positive      277
Negative      266
Irrelevant    172
Name: count, dtype: int64

In [13]:
# Mostrar la cantidad de elementos nulos:

print(df['text'].isnull().sum())

0

In [14]:
# Eliminar elementos Nulos

df.dropna(inplace=True)

In [21]:
!python -m spacy download es_core_news_sm

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\spacy\__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\spacy\errors.py", line 3, in <module>
    from .compat import Literal
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\spacy\compat.py", line 4, in <module>
    from thinc.util import copy_array
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\thinc\__init__.py", line 5, in <module>
    from .config import registry
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\thinc\config.py", line 5, in <module>
    from .types import Decorator
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\thinc\types.py", line 27, in <module>
    from .compat import cupy, has_cupy
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\thinc\compat.py", line 99, in <module>
    import h5py
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\h5py\__init__.py", line 45, in <module>
    from ._conv import register_converters as _register_converters, \
  File "h5py\\_conv.pyx", line 1, in init h5py._conv
  File "h5py\\h5r.pyx", line 1, in init h5py.h5r
  File "h5py\\h5p.pyx", line 1, in init h5py.h5p
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [22]:
!python -m spacy validate

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\spacy\__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\spacy\errors.py", line 3, in <module>
    from .compat import Literal
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\spacy\compat.py", line 4, in <module>
    from thinc.util import copy_array
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\thinc\__init__.py", line 5, in <module>
    from .config import registry
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\thinc\config.py", line 5, in <module>
    from .types import Decorator
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\thinc\types.py", line 27, in <module>
    from .compat import cupy, has_cupy
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\thinc\compat.py", line 99, in <module>
    import h5py
  File "c:\Users\Soportedrai\anaconda3\Lib\site-packages\h5py\__init__.py", line 45, in <module>
    from ._conv import register_converters as _register_converters, \
  File "h5py\\_conv.pyx", line 1, in init h5py._conv
  File "h5py\\h5r.pyx", line 1, in init h5py.h5r
  File "h5py\\h5p.pyx", line 1, in init h5py.h5p
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [24]:
!pip install https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-3.7.0/es_core_news_sm-3.7.0-py3-none-any.whl

Collecting es-core-news-sm==3.7.0
  Downloading https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-3.7.0/es_core_news_sm-3.7.0-py3-none-any.whl (12.9 MB)
     ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
      --------------------------------------- 0.3/12.9 MB ? eta -:--:--
     - -------------------------------------- 0.5/12.9 MB 1.7 MB/s eta 0:00:08
     - -------------------------------------- 0.5/12.9 MB 1.7 MB/s eta 0:00:08
     --- ------------------------------------ 1.0/12.9 MB 1.0 MB/s eta 0:00:12
     ---- ----------------------------------- 1.3/12.9 MB 1.1 MB/s eta 0:00:11
     ---- ----------------------------------- 1.3/12.9 MB 1.1 MB/s eta 0:00:11
     ---- ----------------------------------- 1.3/12.9 MB 1.1 MB/s eta 0:00:11
     ---- ----------------------------------- 1.3/12.9 MB 1.1 MB/s eta 0:00:11
     ---- ---------------------------------- 1.6/12.9 MB 798.7 kB/s eta 0:00:15
     ----- --------------------------------- 1.8/12.9 MB 811.6 kB/s eta 0:00:14
     ------ -------------------------------- 2.1/12.9 MB 838.7 kB/s eta 0:00:13
     ------- ------------------------------- 2.4/12.9 MB 900.8 kB/s eta 0:00:12
     ------- ------------------------------- 2.6/12.9 MB 926.3 kB/s eta 0:00:12
     -------- ------------------------------ 2.9/12.9 MB 947.7 kB/s eta 0:00:11
     --------- ----------------------------- 3.1/12.9 MB 966.0 kB/s eta 0:00:11
     ---------- ---------------------------- 3.4/12.9 MB 982.1 kB/s eta 0:00:10
     ----------- --------------------------- 3.7/12.9 MB 960.8 kB/s eta 0:00:10
     ------------ --------------------------- 3.9/12.9 MB 1.0 MB/s eta 0:00:09
     ------------- -------------------------- 4.2/12.9 MB 1.0 MB/s eta 0:00:09
     ------------- -------------------------- 4.5/12.9 MB 1.0 MB/s eta 0:00:09
     -------------- ------------------------- 4.7/12.9 MB 1.0 MB/s eta 0:00:08
     --------------- ------------------------ 5.0/12.9 MB 1.0 MB/s eta 0:00:08
     ---------------- ----------------------- 5.2/12.9 MB 1.0 MB/s eta 0:00:08
     ----------------- ---------------------- 5.5/12.9 MB 1.1 MB/s eta 0:00:07
     ----------------- ---------------------- 5.8/12.9 MB 1.1 MB/s eta 0:00:07
     ------------------ --------------------- 6.0/12.9 MB 1.1 MB/s eta 0:00:07
     ------------------- -------------------- 6.3/12.9 MB 1.1 MB/s eta 0:00:07
     -------------------- ------------------- 6.6/12.9 MB 1.1 MB/s eta 0:00:06
     --------------------- ------------------ 6.8/12.9 MB 1.1 MB/s eta 0:00:06
     --------------------- ------------------ 6.8/12.9 MB 1.1 MB/s eta 0:00:06
     --------------------- ------------------ 7.1/12.9 MB 1.1 MB/s eta 0:00:06
     ---------------------- ----------------- 7.3/12.9 MB 1.1 MB/s eta 0:00:06
     ----------------------- ---------------- 7.6/12.9 MB 1.1 MB/s eta 0:00:05
     ------------------------ --------------- 7.9/12.9 MB 1.1 MB/s eta 0:00:05
     ------------------------- -------------- 8.1/12.9 MB 1.1 MB/s eta 0:00:05
     -------------------------- ------------- 8.4/12.9 MB 1.1 MB/s eta 0:00:05
     -------------------------- ------------- 8.7/12.9 MB 1.1 MB/s eta 0:00:04
     --------------------------- ------------ 8.9/12.9 MB 1.1 MB/s eta 0:00:04
     --------------------------- ------------ 8.9/12.9 MB 1.1 MB/s eta 0:00:04
     ----------------------------- ---------- 9.4/12.9 MB 1.1 MB/s eta 0:00:04
     ------------------------------ --------- 9.7/12.9 MB 1.1 MB/s eta 0:00:03
     ------------------------------ --------- 10.0/12.9 MB 1.1 MB/s eta 0:00:03
     ------------------------------- -------- 10.2/12.9 MB 1.1 MB/s eta 0:00:03
     -------------------------------- ------- 10.5/12.9 MB 1.1 MB/s eta 0:00:03
     --------------------------------- ------ 10.7/12.9 MB 1.1 MB/s eta 0:00:02
     ---------------------------------- ----- 11.0/12.9 MB 1.1 MB/s eta 0:00:02
     ---------------------------------- ----- 11.3/12.9 MB 1.1 MB/s eta 0:00:02
     ----------------------------------- ---- 11.5/12.9 MB 1.1 MB/s eta 0:00:02
     ------------------------------------ --- 11.8/12.9 MB 1.1 MB/s eta 0:00:01
     ------------------------------------- -- 12.1/12.9 MB 1.1 MB/s eta 0:00:01
     -------------------------------------- - 12.3/12.9 MB 1.1 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.9 MB 1.1 MB/s eta 0:00:01
     ---------------------------------------  12.8/12.9 MB 1.1 MB/s eta 0:00:01
     ---------------------------------------- 12.9/12.9 MB 1.1 MB/s eta 0:00:00
Collecting spacy<3.8.0,>=3.7.0 (from es-core-news-sm==3.7.0)
  Downloading spacy-3.7.5-cp312-cp312-win_amd64.whl.metadata (27 kB)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (3.0.10)
Collecting thinc<8.3.0,>=8.2.2 (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0)
  Downloading thinc-8.2.5-cp312-cp312-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (0.9.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (4.66.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (2.8.2)
Requirement already satisfied: jinja2 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (3.1.4)
Requirement already satisfied: setuptools in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (75.1.0)
Requirement already satisfied: packaging>=20.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (24.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (3.5.0)
Requirement already satisfied: numpy>=1.19.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (2.3.1)
Requirement already satisfied: language-data>=1.2 in c:\users\soportedrai\anaconda3\lib\site-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (1.3.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\soportedrai\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\soportedrai\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\soportedrai\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (2025.4.26)
Collecting blis<0.8.0,>=0.7.8 (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0)
  Downloading blis-0.7.11-cp312-cp312-win_amd64.whl.metadata (7.6 kB)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (0.1.5)
Collecting numpy>=1.19.0 (from spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0)
  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Requirement already satisfied: colorama in c:\users\soportedrai\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (0.4.6)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (8.1.7)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (0.21.1)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (5.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from jinja2->spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (2.1.3)
Requirement already satisfied: marisa-trie>=1.1.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.0->es-core-news-sm==3.7.0) (1.2.1)
Downloading spacy-3.7.5-cp312-cp312-win_amd64.whl (11.7 MB)
   ---------------------------------------- 0.0/11.7 MB ? eta -:--:--
    --------------------------------------- 0.3/11.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.7 MB 1.4 MB/s eta 0:00:08
   - -------------------------------------- 0.5/11.7 MB 1.4 MB/s eta 0:00:08
   --- ------------------------------------ 1.0/11.7 MB 1.0 MB/s eta 0:00:11
   --- ------------------------------------ 1.0/11.7 MB 1.0 MB/s eta 0:00:11
   ---- ----------------------------------- 1.3/11.7 MB 1.0 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/11.7 MB 1.0 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/11.7 MB 1.0 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/11.7 MB 1.0 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/11.7 MB 1.0 MB/s eta 0:00:10
   ----- ---------------------------------- 1.6/11.7 MB 640.3 kB/s eta 0:00:16
   ------- -------------------------------- 2.1/11.7 MB 777.9 kB/s eta 0:00:13
   -------- ------------------------------- 2.4/11.7 MB 833.5 kB/s eta 0:00:12
   -------- ------------------------------- 2.4/11.7 MB 833.5 kB/s eta 0:00:12
   -------- ------------------------------- 2.6/11.7 MB 798.9 kB/s eta 0:00:12
   -------- ------------------------------- 2.6/11.7 MB 798.9 kB/s eta 0:00:12
   ---------- ----------------------------- 3.1/11.7 MB 823.9 kB/s eta 0:00:11
   ----------- ---------------------------- 3.4/11.7 MB 860.4 kB/s eta 0:00:10
   ------------ --------------------------- 3.7/11.7 MB 879.5 kB/s eta 0:00:10
   ------------- -------------------------- 3.9/11.7 MB 896.4 kB/s eta 0:00:09
   -------------- ------------------------- 4.2/11.7 MB 911.9 kB/s eta 0:00:09
   --------------- ------------------------ 4.5/11.7 MB 925.7 kB/s eta 0:00:08
   ---------------- ----------------------- 4.7/11.7 MB 938.2 kB/s eta 0:00:08
   ----------------- ---------------------- 5.0/11.7 MB 949.6 kB/s eta 0:00:08
   ----------------- ---------------------- 5.2/11.7 MB 960.2 kB/s eta 0:00:07
   ------------------ --------------------- 5.5/11.7 MB 969.8 kB/s eta 0:00:07
   ------------------- -------------------- 5.8/11.7 MB 978.7 kB/s eta 0:00:07
   -------------------- ------------------- 6.0/11.7 MB 986.9 kB/s eta 0:00:06
   --------------------- ------------------ 6.3/11.7 MB 994.6 kB/s eta 0:00:06
   ---------------------- ----------------- 6.6/11.7 MB 1.0 MB/s eta 0:00:06
   ----------------------- ---------------- 6.8/11.7 MB 1.0 MB/s eta 0:00:05
   ------------------------ --------------- 7.1/11.7 MB 1.0 MB/s eta 0:00:05
   ------------------------- -------------- 7.3/11.7 MB 1.0 MB/s eta 0:00:05
   -------------------------- ------------- 7.6/11.7 MB 1.0 MB/s eta 0:00:04
   -------------------------- ------------- 7.9/11.7 MB 1.0 MB/s eta 0:00:04
   --------------------------- ------------ 8.1/11.7 MB 1.0 MB/s eta 0:00:04
   ---------------------------- ----------- 8.4/11.7 MB 1.0 MB/s eta 0:00:04
   ----------------------------- ---------- 8.7/11.7 MB 1.0 MB/s eta 0:00:03
   ------------------------------ --------- 8.9/11.7 MB 1.1 MB/s eta 0:00:03
   ------------------------------- -------- 9.2/11.7 MB 1.1 MB/s eta 0:00:03
   -------------------------------- ------- 9.4/11.7 MB 1.1 MB/s eta 0:00:03
   --------------------------------- ------ 9.7/11.7 MB 1.1 MB/s eta 0:00:02
   ---------------------------------- ----- 10.0/11.7 MB 1.1 MB/s eta 0:00:02
   ----------------------------------- ---- 10.2/11.7 MB 1.1 MB/s eta 0:00:02
   ----------------------------------- ---- 10.5/11.7 MB 1.1 MB/s eta 0:00:02
   ------------------------------------ --- 10.7/11.7 MB 1.1 MB/s eta 0:00:01
   ------------------------------------- -- 11.0/11.7 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 11.3/11.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  11.5/11.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 11.7/11.7 MB 1.1 MB/s eta 0:00:00
Downloading thinc-8.2.5-cp312-cp312-win_amd64.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   -------------- ------------------------- 0.5/1.4 MB 1.3 MB/s eta 0:00:01
   --------------------- ------------------ 0.8/1.4 MB 1.2 MB/s eta 0:00:01
   ---------------------------- ----------- 1.0/1.4 MB 1.2 MB/s eta 0:00:01
   ------------------------------------ --- 1.3/1.4 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 1.2 MB/s eta 0:00:00
Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
Downloading blis-0.7.11-cp312-cp312-win_amd64.whl (6.6 MB)
   ---------------------------------------- 0.0/6.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/6.6 MB ? eta -:--:--
   --- ------------------------------------ 0.5/6.6 MB 1.2 MB/s eta 0:00:06
   ---- ----------------------------------- 0.8/6.6 MB 1.2 MB/s eta 0:00:05
   ------ --------------------------------- 1.0/6.6 MB 1.2 MB/s eta 0:00:05
   ------- -------------------------------- 1.3/6.6 MB 1.2 MB/s eta 0:00:05
   ------- -------------------------------- 1.3/6.6 MB 1.2 MB/s eta 0:00:05
   --------- ------------------------------ 1.6/6.6 MB 998.3 kB/s eta 0:00:06
   ----------- ---------------------------- 1.8/6.6 MB 1.1 MB/s eta 0:00:05
   ------------ --------------------------- 2.1/6.6 MB 1.1 MB/s eta 0:00:05
   -------------- ------------------------- 2.4/6.6 MB 1.1 MB/s eta 0:00:04
   --------------- ------------------------ 2.6/6.6 MB 1.1 MB/s eta 0:00:04
   ----------------- ---------------------- 2.9/6.6 MB 1.1 MB/s eta 0:00:04
   ------------------ --------------------- 3.1/6.6 MB 1.1 MB/s eta 0:00:04
   -------------------- ------------------- 3.4/6.6 MB 1.1 MB/s eta 0:00:03
   ---------------------- ----------------- 3.7/6.6 MB 1.1 MB/s eta 0:00:03
   ----------------------- ---------------- 3.9/6.6 MB 1.2 MB/s eta 0:00:03
   ------------------------- -------------- 4.2/6.6 MB 1.2 MB/s eta 0:00:03
   -------------------------- ------------- 4.5/6.6 MB 1.2 MB/s eta 0:00:02
   ---------------------------- ----------- 4.7/6.6 MB 1.2 MB/s eta 0:00:02
   ------------------------------ --------- 5.0/6.6 MB 1.2 MB/s eta 0:00:02
   ------------------------------- -------- 5.2/6.6 MB 1.2 MB/s eta 0:00:02
   --------------------------------- ------ 5.5/6.6 MB 1.2 MB/s eta 0:00:01
   ---------------------------------- ----- 5.8/6.6 MB 1.2 MB/s eta 0:00:01
   ------------------------------------ --- 6.0/6.6 MB 1.2 MB/s eta 0:00:01
   ------------------------------------- -- 6.3/6.6 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------  6.6/6.6 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 6.6/6.6 MB 1.2 MB/s eta 0:00:00
Installing collected packages: numpy, blis, thinc, spacy, es-core-news-sm
  Attempting uninstall: numpy
    Found existing installation: numpy 2.3.1
    Uninstalling numpy-2.3.1:
      Successfully uninstalled numpy-2.3.1
  Attempting uninstall: blis
    Found existing installation: blis 1.3.0
    Uninstalling blis-1.3.0:
      Successfully uninstalled blis-1.3.0
  Attempting uninstall: thinc
    Found existing installation: thinc 8.3.6
    Uninstalling thinc-8.3.6:
      Successfully uninstalled thinc-8.3.6
  Attempting uninstall: spacy
    Found existing installation: spacy 3.8.7
    Uninstalling spacy-3.8.7:
      Successfully uninstalled spacy-3.8.7
Successfully installed blis-0.7.11 es-core-news-sm-3.7.0 numpy-1.26.4 spacy-3.7.5 thinc-8.2.5

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Soportedrai\anaconda3\Lib\site-packages\~~mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Soportedrai\anaconda3\Lib\site-packages\~~mpy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Soportedrai\anaconda3\Lib\site-packages\~lis'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Soportedrai\anaconda3\Lib\site-packages\~hinc'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Soportedrai\anaconda3\Lib\site-packages\~pacy'.
  You can safely remove it manually.

In [27]:
pip install spacy==3.7.2

Collecting spacy==3.7.2
  Downloading spacy-3.7.2-cp312-cp312-win_amd64.whl.metadata (26 kB)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (3.0.10)
Requirement already satisfied: thinc<8.3.0,>=8.1.8 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (2.0.10)
Collecting weasel<0.4.0,>=0.1.0 (from spacy==3.7.2)
  Downloading weasel-0.3.4-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (0.9.0)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (5.2.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (4.66.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (2.8.2)
Requirement already satisfied: jinja2 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (3.1.4)
Requirement already satisfied: setuptools in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (75.1.0)
Requirement already satisfied: packaging>=20.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (24.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (3.5.0)
Requirement already satisfied: numpy>=1.19.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from spacy==3.7.2) (1.26.4)
Requirement already satisfied: language-data>=1.2 in c:\users\soportedrai\anaconda3\lib\site-packages (from langcodes<4.0.0,>=3.2.0->spacy==3.7.2) (1.3.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy==3.7.2) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy==3.7.2) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy==3.7.2) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\soportedrai\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy==3.7.2) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\soportedrai\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy==3.7.2) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy==3.7.2) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\soportedrai\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy==3.7.2) (2025.4.26)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in c:\users\soportedrai\anaconda3\lib\site-packages (from thinc<8.3.0,>=8.1.8->spacy==3.7.2) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from thinc<8.3.0,>=8.1.8->spacy==3.7.2) (0.1.5)
Requirement already satisfied: colorama in c:\users\soportedrai\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy==3.7.2) (0.4.6)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\users\soportedrai\anaconda3\lib\site-packages (from typer<0.10.0,>=0.3.0->spacy==3.7.2) (8.1.7)
Collecting cloudpathlib<0.17.0,>=0.7.0 (from weasel<0.4.0,>=0.1.0->spacy==3.7.2)
  Downloading cloudpathlib-0.16.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from jinja2->spacy==3.7.2) (2.1.3)
Requirement already satisfied: marisa-trie>=1.1.0 in c:\users\soportedrai\anaconda3\lib\site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy==3.7.2) (1.2.1)
Downloading spacy-3.7.2-cp312-cp312-win_amd64.whl (11.7 MB)
   ---------------------------------------- 0.0/11.7 MB ? eta -:--:--
    --------------------------------------- 0.3/11.7 MB ? eta -:--:--
    --------------------------------------- 0.3/11.7 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.7 MB 931.2 kB/s eta 0:00:12
   --- ------------------------------------ 1.0/11.7 MB 1.0 MB/s eta 0:00:11
   --- ------------------------------------ 1.0/11.7 MB 1.0 MB/s eta 0:00:11
   ---- ----------------------------------- 1.3/11.7 MB 919.0 kB/s eta 0:00:12
   ----- ---------------------------------- 1.6/11.7 MB 963.8 kB/s eta 0:00:11
   ----- ---------------------------------- 1.6/11.7 MB 963.8 kB/s eta 0:00:11
   ------ --------------------------------- 1.8/11.7 MB 898.8 kB/s eta 0:00:11
   ------- -------------------------------- 2.1/11.7 MB 931.9 kB/s eta 0:00:11
   -------- ------------------------------- 2.4/11.7 MB 958.5 kB/s eta 0:00:10
   -------- ------------------------------- 2.6/11.7 MB 980.2 kB/s eta 0:00:10
   --------- ------------------------------ 2.9/11.7 MB 998.6 kB/s eta 0:00:09
   ---------- ----------------------------- 3.1/11.7 MB 1.0 MB/s eta 0:00:09
   ----------- ---------------------------- 3.4/11.7 MB 1.0 MB/s eta 0:00:09
   ------------ --------------------------- 3.7/11.7 MB 1.0 MB/s eta 0:00:08
   ------------- -------------------------- 3.9/11.7 MB 1.0 MB/s eta 0:00:08
   -------------- ------------------------- 4.2/11.7 MB 1.1 MB/s eta 0:00:08
   --------------- ------------------------ 4.5/11.7 MB 1.1 MB/s eta 0:00:07
   ---------------- ----------------------- 4.7/11.7 MB 1.1 MB/s eta 0:00:07
   ----------------- ---------------------- 5.0/11.7 MB 1.1 MB/s eta 0:00:07
   ----------------- ---------------------- 5.2/11.7 MB 1.1 MB/s eta 0:00:06
   ----------------- ---------------------- 5.2/11.7 MB 1.1 MB/s eta 0:00:06
   ------------------- -------------------- 5.8/11.7 MB 1.1 MB/s eta 0:00:06
   -------------------- ------------------- 6.0/11.7 MB 1.1 MB/s eta 0:00:06
   --------------------- ------------------ 6.3/11.7 MB 1.1 MB/s eta 0:00:05
   --------------------- ------------------ 6.3/11.7 MB 1.1 MB/s eta 0:00:05
   ---------------------- ----------------- 6.6/11.7 MB 1.1 MB/s eta 0:00:05
   ----------------------- ---------------- 6.8/11.7 MB 1.1 MB/s eta 0:00:05
   ------------------------ --------------- 7.1/11.7 MB 1.1 MB/s eta 0:00:05
   ------------------------- -------------- 7.3/11.7 MB 1.1 MB/s eta 0:00:04
   -------------------------- ------------- 7.6/11.7 MB 1.1 MB/s eta 0:00:04
   -------------------------- ------------- 7.9/11.7 MB 1.1 MB/s eta 0:00:04
   --------------------------- ------------ 8.1/11.7 MB 1.1 MB/s eta 0:00:04
   ---------------------------- ----------- 8.4/11.7 MB 1.1 MB/s eta 0:00:03
   ----------------------------- ---------- 8.7/11.7 MB 1.1 MB/s eta 0:00:03
   ------------------------------ --------- 8.9/11.7 MB 1.1 MB/s eta 0:00:03
   ------------------------------- -------- 9.2/11.7 MB 1.1 MB/s eta 0:00:03
   -------------------------------- ------- 9.4/11.7 MB 1.1 MB/s eta 0:00:02
   --------------------------------- ------ 9.7/11.7 MB 1.1 MB/s eta 0:00:02
   ---------------------------------- ----- 10.0/11.7 MB 1.1 MB/s eta 0:00:02
   ----------------------------------- ---- 10.2/11.7 MB 1.1 MB/s eta 0:00:02
   ----------------------------------- ---- 10.5/11.7 MB 1.1 MB/s eta 0:00:02
   ------------------------------------ --- 10.7/11.7 MB 1.1 MB/s eta 0:00:01
   ------------------------------------- -- 11.0/11.7 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 11.3/11.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  11.5/11.7 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 11.7/11.7 MB 1.1 MB/s eta 0:00:00
Downloading weasel-0.3.4-py3-none-any.whl (50 kB)
Downloading cloudpathlib-0.16.0-py3-none-any.whl (45 kB)
Installing collected packages: cloudpathlib, weasel, spacy
  Attempting uninstall: cloudpathlib
    Found existing installation: cloudpathlib 0.21.1
    Uninstalling cloudpathlib-0.21.1:
      Successfully uninstalled cloudpathlib-0.21.1
  Attempting uninstall: weasel
    Found existing installation: weasel 0.4.1
    Uninstalling weasel-0.4.1:
      Successfully uninstalled weasel-0.4.1
  Attempting uninstall: spacy
    Found existing installation: spacy 3.7.5
    Uninstalling spacy-3.7.5:
      Successfully uninstalled spacy-3.7.5
Successfully installed cloudpathlib-0.16.0 spacy-3.7.2 weasel-0.3.4
Note: you may need to restart the kernel to use updated packages.

In [26]:
import es_core_news_sm
nlp = es_core_news_sm.load()

ModuleNotFoundError: No module named 'spacy.pipeline.factories'

In [ ]:
# Funcion para preprocesar los datos de texto

def preprocess(text):
    #Eliminar Stoprwords:
    doc = nlp(text)
    filtered_tokens = []
    for token in doc:
        if token.is_stop or token.is_punct:
            continue 
        filtered_tokens.append(token.lemma_)                # Agrega el texto lemalizado  
    return ' '.join(filtered_tokens)

OSError: [E050] Can't find model 'es_core_news_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

In [ ]:
df['texto preprocesado'] = df['text'].apply(preprocess)

NameError: name 'df' is not defined

In [ ]:
df

,id,brand,label,text,texto preprocesado
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...,i am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...,im getting on borderlands and i will kill you all
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...,im getting on borderlands 2 and i will murder ...
...,...,...,...,...,...
74677,9200,Nvidia,Positive,Just realized that the Windows partition of my...,Just realized that the Windows partition of my...
74678,9200,Nvidia,Positive,Just realized that my Mac window partition is ...,Just realized that my Mac window partition is ...
74679,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...,Just realized the windows partition of my Mac ...
74680,9200,Nvidia,Positive,Just realized between the windows partition of...,Just realized betweir the windows partition of...
74681,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...,Just like the windows partition of my Mac is l...

# Codificamos la columna objetivo (Target)

In [ ]:
le_model = LabelEncoder()
df['label'] = le_model.fit.transform(df['label'])

AttributeError: 'function' object has no attribute 'transform'

In [ ]:
df.head()

NameError: name 'df' is not defined

## *NAIVES BAYES PARA CLASIFICACIÓN DE TWEETS

In [ ]:
# Hiperparámetros del modelo: clasificador Naive Bayes
clf = pipeline ([
    ('vectorizer_tri_grams', TfidfVectorizer()),
    ('naives_bayes', MultinomialNB())
    ])

NameError: name 'pipeline' is not defined

In [ ]:
# Entranar el modelo de bayes:
clf.fit(X_train, y_train)

NameError: name 'clf' is not defined

In [9]:
y_pred = clf.predict(X_test)
# Confianza del modelo:
print(f'Confianza en random forest: {accuracy_score(y_test, y_pred)}\n')
print(f'Clasificación en random forest:\n{classification_report(y_test, y_pred)}\n')

NameError: name 'clf' is not defined